### ISSUE TITLE
本地运行游戏领取流量失败

### ISSUE THREAD

**Issue by a753005179** [simo8102/chinaunicom-AutoSignMachine#211]
版本号：（请贴出你的版本号，请确认是否已通过升级到最新版来解决当前问题？）
运行环境：（本地，Win10

问题描述：

日志信息：dailygameflow: [✅🤩🍗] 正在领取奖励 * 1
dailygameflow: 任务错误： Error: [非开发模式，隐藏请求错误信息]
    at axiosRetryInterceptor (F:\88-AutoSignMachine-main\utils\request.js:83:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.gameFlowGet (F:\88-AutoSignMachine-main\commands\tasks\unicom\producGame.js:543:24)
    at async Object.doGameFlowTask (F:\88-AutoSignMachine-main\commands\tasks\unicom\producGame.js:446:13)
    at async Object.<anonymous> (F:\88-AutoSignMachine-main\commands\tasks\unicom\unicom.js:63:5)
    at async F:\88-AutoSignMachine-main\utils\scheduler.js:315:29
    at async run (F:\88-AutoSignMachine-main\node_modules\p-queue\dist\index.js:163:29)

**Comment by a753005179** [comment]
之前是可以的，5月10号突然不行了

**Comment by simo8102** [comment]
脚本是否最新

**Comment by Disky** [comment]
网络错误也是报这个错
