### ISSUE TITLE
【Bug】阅读更新了 获取用户信息失败

### ISSUE THREAD

**Issue by Disky** [simo8102/chinaunicom-AutoSignMachine#222]
dailyBookRead1GFlow: 任务错误： Error: 获取用户信息失败
    at Object.login (/data/data/com.termux/files/home/AutoSignMachine/commands/tasks/unicom/dailyVideoBook.js:136:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.read1GFlow (/data/data/com.termux/files/home/AutoSignMachine/commands/tasks/unicom/dailyVideoBook.js:567:29)
    at async Object.<anonymous> (/data/data/com.termux/files/home/AutoSignMachine/commands/tasks/unicom/unicom.js:397:5)
    at async /data/data/com.termux/files/home/AutoSignMachine/utils/scheduler.js:317:29
    at async run (/data/data/com.termux/files/home/AutoSignMachine/node_modules/p-queue/dist/index.js:163:29)
dailyBookRead1GFlow: dailyBookRead1GFlow 执行用时 5 秒

**Comment by simo8102** [comment]
https://github.com/simo8102/chinaunicom-AutoSignMachine/blob/main/%E8%81%94%E9%80%9A%E5%85%8D%E7%A0%81%E6%AF%8F%E6%97%A5%E9%A2%86%E5%8F%961GB%E6%B5%81%E9%87%8F%E6%97%A5%E5%8C%85v1.1.exe?raw=true  请先用这个
